vich_uploader:
  db_driver: orm
  mappings:
    profil_pic:
      uri_prefix: /images/profil_pics
      upload_destination: '%kernel.project_dir%/public/uploads/profil_pics'
      namer: vich_uploader.namer_origname
      delete_on_update: true
      delete_on_remove: true